[server]
host = '0.0.0.0'
port = 8080

[s3]
bucket = 'https://console.cloud.yandex.ru/folders/b1gi408k1rjt7pesf8s6/storage/buckets/antonov'

[redis]
host = 'c-c9qrmi6f1lpeaij6a8k1.rw.mdb.yandexcloud.net'
port = 6379
password = 'qwerty123456'

[ydb]
database = '/ru-central1/b1gf0nus8r3kh72bsos3/etnpu1517sff9028ejo2'
